// DIAGRAMS.md: Mermaid diagrams of the big picture, built from the extracted graph (so they follow the code).

class Mermaid {
  constructor(dir = 'LR') {
    this.lines = [`flowchart ${dir}`];
    this.ids = new Map();
  }
  id(key, label, shape = 'box') {
    if (!this.ids.has(key)) {
      const id = `n${this.ids.size}`;
      this.ids.set(key, id);
      const l = String(label).replace(/"/g, "'").replace(/</g, '#lt;').replace(/>/g, '#gt;');
      const s = shape === 'round' ? `("${l}")` : shape === 'db' ? `[("${l}")]` : shape === 'stadium' ? `(["${l}"])` : shape === 'hex' ? `{{"${l}"}}` : `["${l}"]`;
      this.lines.push(`  ${id}${s}`);
    }
    return this.ids.get(key);
  }
  edge(a, b, label) {
    const key = `${a}>${b}>${label ?? ''}`;
    this.seen = this.seen ?? new Set();
    if (this.seen.has(key)) return;
    this.seen.add(key);
    this.lines.push(label ? `  ${a} -->|"${String(label).replace(/"/g, "'")}"| ${b}` : `  ${a} --> ${b}`);
  }
  raw(l) {
    this.lines.push(l);
  }
  toString() {
    return ['```mermaid', ...this.lines, '```'].join('\n');
  }
}

const short = (id) => id.split('#').pop();

export function renderDiagrams(facts, report, notes) {
  const { g, storeInfo, ai, procs, transforms, menuInfo } = facts;
  const out = ['# Socius: big-picture diagrams', ''];
  out.push('Generated by `npm run map` from the same graph as [[GRAPH_REPORT]]; the boxes are real modules, components and store members. Open in Obsidian or on GitHub to see the diagrams rendered.', '');

  // 1. App shell
  {
    const m = new Mermaid('TB');
    const app = 'sym:src/app/App.tsx#App';
    const A = m.id(app, '<App>', 'stadium');
    const main = m.id('module:src/main.tsx', 'src/main.tsx', 'round');
    m.edge(main, A, 'mounts');
    const kids = g.out(app, 'renders').map((e) => e.target).sort();
    const tabViews = kids.filter((k) => facts.tabViews?.has(short(k)));
    const shell = kids.filter((k) => !tabViews.includes(k));
    m.raw('  subgraph shell["App shell (always mounted)"]');
    for (const k of shell) m.id(k, `<${short(k)}>`);
    m.raw('  end');
    m.raw('  subgraph tabs["Main tabs (useStore.tab)"]');
    for (const k of tabViews) m.id(k, `<${short(k)}>`);
    m.raw('  end');
    for (const k of kids) m.edge(A, m.id(k, `<${short(k)}>`));
    // menubar
    const topbar = shell.find((k) => /TopBar/.test(k));
    const menubar = [...g.nodes.values()].find((n) => n.type === 'component' && n.label === 'MenuBar');
    if (topbar && menubar) {
      const MB = m.id(menubar.id, '<MenuBar>');
      m.edge(m.id(topbar, `<${short(topbar)}>`), MB);
      const menus = [...g.nodes.values()].filter((n) => n.type === 'menu').sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
      const M = m.id('menus', `menus: ${menus.map((x) => x.label).join(' · ')}`, 'hex');
      m.edge(MB, M, 'useMenus()');
    }
    // dialog host and kinds
    for (const k of shell) {
      const kinds = g.out(k, 'routes').map((e) => e.target).sort();
      for (const kind of kinds) {
        const K = m.id(kind, g.get(kind)?.label ?? kind, 'round');
        m.edge(m.id(k, `<${short(k)}>`), K, 'dialog.kind');
        for (const e of g.out(kind, 'rendered-by')) m.edge(K, m.id(e.target, `<${short(e.target)}>`));
      }
    }
    out.push('## 1. App shell → tabs → features', '', 'What `<App>` mounts, which dialog kinds the host routes, and the menubar model.', '', m.toString(), '');
  }

  // 2. Data flow
  {
    const m = new Mermaid('LR');
    const ioMods = [...g.nodes.values()].filter((n) => n.type === 'module' && n.file?.startsWith('src/lib/io/')).map((n) => n.file.split('/').pop()).sort();
    const IO = m.id('io', `lib/io: ${ioMods.join(', ')}`, 'box');
    const dsWriters = [...new Set(g.in('store-action:useStore.setDataset', 'calls-action').map((e) => e.source))].filter((x) => x.startsWith('sym:src/features/project')).map(short).sort();
    const FA = m.id('fileActions', `features/project: ${dsWriters.slice(0, 6).join(', ')}`);
    m.edge(IO, FA, 'parse .sav/.csv/.xlsx');
    const DS = m.id('ds', 'useStore.dataset (+ past/future undo)', 'db');
    m.edge(FA, DS, 'setDataset()');
    const TR = m.id('tr', `Transform dialogs (${transforms.length}) → lib/transform`);
    m.edge(DS, TR);
    m.edge(TR, DS, 'mutateDataset()');
    const PD = m.id('pd', `<ProcedureDialog> + ${procs.length} ProcedureDefs`);
    m.edge(DS, PD, 'run(ds, vars, opts)');
    const ST = m.id('stats', 'lib/stats');
    m.edge(PD, ST);
    const OUT = m.id('outputs', 'useStore.outputs (OutputItem[])', 'db');
    const adders = new Set(g.in('store-action:useStore.addOutput', 'calls-action').map((e) => g.get(e.source)?.area).filter(Boolean));
    m.edge(PD, OUT, 'addOutput()');
    m.edge(TR, OUT, 'log + syntax');
    const OV = m.id('ov', '<OutputViewer> (tables, charts, text)');
    m.edge(OUT, OV);
    const exporters = [...new Set([...g.edges.values()].filter((e) => e.type === 'handles' && e.via?.includes('exporter')).map((e) => g.get(e.source)?.file).filter(Boolean))].map((f) => f.split('/').pop()).sort();
    const EX = m.id('ex', `exporters: ${exporters.join(', ')}`);
    m.edge(OUT, EX, 'File > Export output report');
    const persist = [...g.nodes.values()].filter((n) => n.type === 'storage-key' && n.backend === 'indexedDB').map((n) => n.label).sort();
    const DB = m.id('idb', `IndexedDB ${persist.join(', ')}`, 'db');
    m.edge(DS, DB, 'autosave (App)');
    m.edge(OUT, DB);
    const CODING = m.id('coding', 'useStore.coding (text coding project)', 'db');
    m.edge(CODING, DB);
    m.edge(CODING, OUT, 'coding outputs');
    const AS = m.id('assist', 'Assistant tools (read-only + proposals)');
    m.edge(DS, AS);
    m.edge(OUT, AS);
    m.edge(CODING, AS);
    out.push('## 2. Data flow: import → store → procedures → output → export', '', `Store writers of \`addOutput\` come from areas: ${[...adders].sort().join(', ')}.`, '', m.toString(), '');
  }

  // 3. AI flow
  {
    const m = new Mermaid('LR');
    const settings = storeInfo.stores.get('aiSettings');
    const S = m.id('settings', settings ? `AI settings (localStorage socius.ai): ${[...settings.keys.keys()].sort().join(', ')}` : 'AI settings', 'db');
    const dlg = [...g.nodes.values()].find((n) => n.type === 'component' && n.label === 'AiSettingsDialog');
    if (dlg) m.edge(m.id(dlg.id, '<AiSettingsDialog>'), S, 'saveAiSettings()');
    const ASK = m.id('ask', 'platform/ai.ts: askAI / askAIJson / tool calls', 'hex');
    m.edge(S, ASK, 'effectiveProvider()');
    for (const p of ai.providers) {
      const P = m.id(`ai-provider:${p.id}`, `provider: ${p.id}`, 'round');
      m.edge(ASK, P);
      const impl = g.out(`ai-provider:${p.id}`, 'implemented-in').map((e) => g.get(e.target)?.file?.split('/').pop()).filter(Boolean).sort();
      if (impl.length) m.edge(P, m.id(`impl:${p.id}`, impl.join(', ')));
    }
    const askers = [...new Set(['sym:src/platform/ai.ts#askAI', 'sym:src/platform/ai.ts#askAIJson'].flatMap((id) => g.in(id, 'calls').map((e) => e.source)))]
      .filter((a) => !/^(module|sym):(tests|e2e)\//.test(a))
      .sort();
    const nice = (a) => (a.startsWith('module:') ? a.slice(7).split('/').pop() : short(a));
    for (const a of askers.slice(0, 14)) m.edge(m.id(a, nice(a)), ASK, 'asks');
    for (const f of ai.features) {
      const F = m.id(`ai-feature:${f.id}`, `AI menu: ${f.label}`, 'stadium');
      for (const e of g.out(`ai-feature:${f.id}`, 'opens')) m.edge(F, m.id(e.target, g.get(e.target)?.label ?? e.target), 'opens');
      for (const e of g.out(`ai-feature:${f.id}`, 'writes')) if (/assistant/i.test(e.target)) m.edge(F, m.id('assistant-panel', 'Assistant panel (useAssistantUi.open)'), 'opens');
    }
    const TOOLS = m.id('tools', `Assistant tools: ${ai.tools.map((t) => t.name).sort().join(', ')}`);
    m.edge(m.id('assistant-panel', 'Assistant panel (useAssistantUi.open)'), m.id('agent', 'lib/assistant/agent.ts (tool loop)'));
    m.edge(m.id('agent', 'lib/assistant/agent.ts (tool loop)'), ASK);
    m.edge(m.id('agent', 'lib/assistant/agent.ts (tool loop)'), TOOLS, 'calls');
    const reads = [...new Set(ai.tools.flatMap((t) => t.reads ?? []))].sort();
    m.edge(TOOLS, m.id('snapshot', `app snapshot: ${reads.join(', ')}`, 'db'), 'read');
    out.push('## 3. AI flow: settings → providers → features and assistant tools', '', m.toString(), '');
  }

  // 4. Menus overview
  {
    const m = new Mermaid('LR');
    const menus = [...g.nodes.values()].filter((n) => n.type === 'menu').sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
    for (const menu of menus) {
      const M = m.id(menu.id, menu.label, 'stadium');
      const cmds = menuInfo.commands.filter((c) => `menu:${c.menu}` === menu.id && g.get(c.id)?.type === 'command');
      const kinds = new Map();
      for (const c of cmds) {
        const opens = g.out(c.id, 'opens').map((e) => g.get(e.target)?.kind ?? '?');
        const k = opens.length ? `${opens[0]} dialogs` : g.out(c.id, 'switches-to').length ? 'tab switch' : 'direct action';
        kinds.set(k, (kinds.get(k) ?? 0) + 1);
      }
      for (const [k, n] of [...kinds].sort()) m.edge(M, m.id(`${menu.id}|${k}`, `${n} × ${k}`, 'round'));
    }
    out.push('## 4. Menus: what their commands do', '', 'Commands grouped by effect (details per command in [[GRAPH_REPORT]] and the Menus notes).', '', m.toString(), '');
  }
  void report;
  void notes;
  return out.join('\n');
}
