// Writers: the Obsidian vault (notes with YAML front matter and [[wikilinks]]), graph.json, GRAPH_REPORT.md,
// DIAGRAMS.md, README.md and Home.md. Output is sorted and has no timestamps, so regenerating an
// unchanged codebase produces no diff.

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { Graph } from './graph.mjs';
import { renderReport } from './report.mjs';
import { renderDiagrams } from './diagrams.mjs';
import { renderReadme, renderHome, OBSIDIAN_GRAPH } from './readme.mjs';

// Edge vocabulary: outgoing heading, incoming heading.
export const EDGE_LABELS = {
  'in-area': ['Area', 'Modules'],
  contains: ['Defines', 'Defined in'],
  imports: ['Imports', 'Imported by'],
  calls: ['Calls', 'Called by'],
  renders: ['Renders', 'Rendered by'],
  uses: ['Uses', 'Used by'],
  reads: ['Reads', 'Read by'],
  writes: ['Writes', 'Written by'],
  removes: ['Removes', 'Removed by'],
  listens: ['Listens to changes of', 'Change listeners'],
  'calls-action': ['Calls store actions', 'Called by'],
  'has-key': ['State keys', 'Store'],
  'has-action': ['Actions', 'Store'],
  opens: ['Opens', 'Opened by'],
  'rendered-by': ['Rendered by', 'Renders'],
  routes: ['Routes dialog kind', 'Routed by'],
  'part-of': ['Part of', 'Items'],
  defines: ['Defines', 'Defined by'],
  'switches-to': ['Switches to', 'Switched to by'],
  'tested-by': ['Tested by', 'Tests'],
  'logged-by': ['Logged to Output by', 'Logs'],
  'generates-syntax': ['Generates SPSS syntax', 'Generated by'],
  'implemented-by': ['Implemented by', 'Implements'],
  'implemented-in': ['Implemented in', 'Implements provider'],
  'configured-in': ['Configured in dialog', 'Configures'],
  creates: ['Creates', 'Created by'],
  handles: ['Handles', 'Handled by'],
  'has-variant': ['Variants', 'Variant of'],
  'documented-in': ['Documented in', 'Documents shortcut'],
  'bound-in': ['Bound in', 'Binds shortcut'],
  throws: ['Produces error code', 'Produced by'],
  explains: ['Explains error code', 'Explained by'],
  checks: ['Checks error code', 'Checked by'],
  'started-by': ['Started by', 'Starts'],
  lists: ['Lists', 'Listed by'],
  suggests: ['Suggests', 'Suggested by'],
  'requires-permission': ['Requires permission', 'Required by'],
  references: ['References', 'Referenced by (build config)'],
};
const EDGE_ORDER = Object.keys(EDGE_LABELS);

const NOTE_TYPES = new Set([
  'area', 'module', 'test', 'test-helper', 'e2e-spec', 'component', 'hook', 'store', 'store-key', 'store-action', 'menu', 'submenu', 'command',
  'dialog', 'dialog-kind', 'shortcut', 'procedure', 'transform', 'syntax', 'ai-provider', 'ai-feature', 'ai-error', 'ai-tool', 'ai-prompt',
  'storage-key', 'output-kind', 'chart-type', 'output-source', 'palette-source', 'package',
]);
// Top-level notes that must never be shadowed by a short link.
const RESERVED = new Set(['readme', 'home', 'graph_report', 'diagrams']);
const MODULE_TYPES = new Set(['module', 'test', 'test-helper', 'e2e-spec']);
const HEADING_TYPES = new Set(['function', 'const', 'class', 'type', 'interface', 'enum', 'component', 'hook', 'store']);

/** In Markdown table rows, a wikilink's alias pipe must be escaped (\\|) or it splits the cell. */
export function escapeTableLinks(text) {
  return text
    .split('\n')
    .map((l) => (l.startsWith('|') ? l.replace(/\[\[([^\]|]*?)\|([^\]]*?)\]\]/g, '[[$1\\|$2]]') : l))
    .join('\n');
}

export const sanitize = (s) =>
  String(s)
    .replace(/[\\/:*?"<>|#^[\]]/g, '-')
    .replace(/\s+/g, ' ')
    .replace(/[. ]+$/, '')
    .trim() || '_';

/** Assigns every node a note path (or a heading inside its module's note, or nothing). */
export class Notes {
  constructor(g) {
    this.g = g;
    this.paths = new Map();
    const used = new Map();
    const claim = (id, p) => {
      // never shadow the top-level notes (README, Home, GRAPH_REPORT, DIAGRAMS)
      if (RESERVED.has(p.split('/').pop().toLowerCase())) p = `${p} (${g.get(id)?.type ?? 'note'})`;
      let q = p;
      let i = 2;
      while (used.has(q.toLowerCase())) q = `${p} (${i++})`;
      used.set(q.toLowerCase(), id);
      this.paths.set(id, q);
    };
    const nodes = g.sortedNodes();
    // components and hooks: disambiguate by folder when names clash
    const nameCount = new Map();
    for (const n of nodes) if (n.type === 'component' || n.type === 'hook' || n.type === 'ai-prompt') nameCount.set(`${n.type}|${n.label}`, (nameCount.get(`${n.type}|${n.label}`) ?? 0) + 1);
    const where = (n) => (n.file ?? '').replace(/^src\//, '').replace(/\.[jt]sx?$/, '').replace(/\//g, '-');
    for (const n of nodes) {
      if (!NOTE_TYPES.has(n.type)) continue;
      if (n.type === 'store' && !n.id.startsWith('settings:') && !n.id.startsWith('sym:')) continue;
      let p;
      switch (n.type) {
        case 'area':
          p = `Areas/${sanitize(n.label.replace(/\//g, ' - '))}`;
          break;
        case 'module':
        case 'test':
        case 'test-helper':
        case 'e2e-spec':
          p = `Code/${n.file.split('/').map(sanitize).join('/')}`;
          break;
        case 'component':
          p = `Components/${sanitize(n.label)}${nameCount.get(`component|${n.label}`) > 1 ? ` (${where(n)})` : ''}`;
          break;
        case 'hook':
          p = `Hooks/${sanitize(n.label)}${nameCount.get(`hook|${n.label}`) > 1 ? ` (${where(n)})` : ''}`;
          break;
        case 'store':
          p = `Store/${sanitize(n.id.startsWith('settings:') ? n.id.slice(9) : n.label)}`;
          break;
        case 'store-key':
          p = `Store/${sanitize(n.store)}/${sanitize(n.label.split('.').slice(1).join('.'))}`;
          break;
        case 'store-action':
          p = `Store/${sanitize(n.store)}/${sanitize(n.label.split('.').slice(1).join('.'))}`;
          break;
        case 'menu':
          p = `Menus/${sanitize(n.label)}`;
          break;
        case 'submenu':
        case 'command':
          p = `Menus/${(n.path ?? n.label).split(' > ').map(sanitize).join('/')}`;
          break;
        case 'dialog':
          p = `Dialogs/${sanitize(n.kind)}/${sanitize(n.dialogId)}`;
          break;
        case 'dialog-kind':
          p = `Dialogs/${sanitize(n.id.split(':')[1])} dialogs`;
          break;
        case 'shortcut':
          p = `Shortcuts/${sanitize(n.label)}`;
          break;
        case 'procedure':
          p = `Procedures/${sanitize(n.procedureId)}`;
          break;
        case 'transform':
          p = `Transforms/${sanitize(n.label)}`;
          break;
        case 'syntax':
          p = `Syntax/${sanitize(n.label)}`;
          break;
        case 'ai-provider':
          p = `AI/Providers/${sanitize(n.label)}`;
          break;
        case 'ai-feature':
          p = `AI/Features/${sanitize(n.id.split(':')[1])}`;
          break;
        case 'ai-error':
          p = `AI/Errors/${sanitize(n.label)}`;
          break;
        case 'ai-tool':
          p = `AI/Tools/${sanitize(n.label)}`;
          break;
        case 'ai-prompt':
          p = `AI/Prompts/${sanitize(n.label)}${nameCount.get(`ai-prompt|${n.label}`) > 1 ? ` (${where(n)})` : ''}`;
          break;
        case 'storage-key':
          p = `Storage/${sanitize(n.backend)}/${sanitize(n.label)}`;
          break;
        case 'output-kind':
          p = `Output/Blocks/${sanitize(n.label)}`;
          break;
        case 'chart-type':
          p = `Output/Charts/${sanitize(n.label)}`;
          break;
        case 'output-source':
          p = `Output/Sources/${sanitize(n.id.split(':')[1])}`;
          break;
        case 'palette-source':
          p = `Palette/${sanitize(n.id.split(':')[1])}`;
          break;
        case 'package':
          p = `Packages/${sanitize(n.label)}`;
          break;
        default:
          continue;
      }
      claim(n.id, p);
    }
  }

  /** Shortest path suffix that identifies a note uniquely (Obsidian resolves links by path suffix). */
  short(p) {
    if (!this.shortCache) {
      this.shortCache = new Map();
      const all = [...this.paths.values()];
      const suffixes = new Map();
      for (const q of all) {
        const parts = q.split('/');
        for (let i = 0; i < parts.length; i++) {
          const suf = parts.slice(i).join('/').toLowerCase();
          suffixes.set(suf, (suffixes.get(suf) ?? 0) + 1);
        }
      }
      for (const q of all) {
        const parts = q.split('/');
        let best = q;
        for (let i = parts.length - 1; i >= 0; i--) {
          const suf = parts.slice(i).join('/');
          if (suffixes.get(suf.toLowerCase()) === 1 && !RESERVED.has(suf.toLowerCase())) {
            best = suf;
            break;
          }
        }
        this.shortCache.set(q, best);
      }
    }
    return this.shortCache.get(p) ?? p;
  }

  /** A wikilink for a node id (note, heading in a module note, or inline code when it has no note). */
  link(id, alias) {
    const n = this.g.get(id);
    const p = this.paths.get(id);
    // modules read best as their short path, which is also the link target
    if (p && !alias && n && MODULE_TYPES.has(n.type)) return `[[${this.short(p)}]]`;
    const text = (alias ?? displayName(n, id)).replace(/[|[\]]/g, '/');
    if (p) return this.short(p) === text ? `[[${text}]]` : `[[${this.short(p)}|${text}]]`;
    const folded = this.g.folded?.(id);
    if (folded) {
      const mp = this.paths.get(`module:${folded.file}`);
      const t2 = (alias ?? `${folded.label}${folded.type === 'function' ? '()' : ''}`).replace(/[|[\]]/g, '/');
      if (mp) return `[[${this.short(mp)}|${t2}]]`;
    }
    if (n && HEADING_TYPES.has(n.type) && n.file) {
      const mp = this.paths.get(`module:${n.file}`);
      if (mp) return `[[${this.short(mp)}#${n.label}|${text}]]`;
    }
    return `\`${text}\``;
  }

  /** Replace [[nodeId]] tokens (from the analysis) with real links. */
  resolveTokens(s) {
    return s.replace(/\[\[([a-z][a-z-]*:[^\]|]+)\]\]/g, (m, id) => (this.g.has(id) || this.g.folded?.(id) ? this.link(id) : `\`${id.replace(/^[a-z-]+:/, '')}\``));
  }
}

export function displayName(n, id) {
  if (!n) return id.replace(/^[a-z-]+:/, '');
  switch (n.type) {
    case 'module':
    case 'test':
    case 'test-helper':
    case 'e2e-spec':
      return n.file;
    case 'command':
    case 'submenu':
      return n.path ?? n.label;
    case 'function':
    case 'hook':
      return `${n.label}()`;
    case 'component':
      return `<${n.label}>`;
    default:
      return n.label;
  }
}

function yamlStr(v) {
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  const s = String(v);
  return /^[\w./@-]+$/.test(s) && !/^(true|false|null|yes|no|on|off|\d.*)$/i.test(s) ? s : JSON.stringify(s);
}

function frontMatter(n, extra = {}) {
  const lines = ['---'];
  const fm = { id: jsonId(n.id), type: n.type, file: n.file, line: n.line, area: n.area, ...extra };
  for (const [k, v] of Object.entries(fm)) {
    if (v === undefined || v === null || v === '') continue;
    if (Array.isArray(v)) lines.push(`${k}: [${v.map(yamlStr).join(', ')}]`);
    else lines.push(`${k}: ${yamlStr(v)}`);
  }
  lines.push('---', '');
  return lines.join('\n');
}

const TYPE_TITLES = {
  module: 'Module', test: 'Test file', 'test-helper': 'Test helper', 'e2e-spec': 'End-to-end spec', component: 'React component', hook: 'React hook', store: 'Store',
  'store-key': 'Store state key', 'store-action': 'Store action', menu: 'Top menu', submenu: 'Submenu', command: 'Menu command', dialog: 'Dialog', 'dialog-kind': 'Dialog kind',
  shortcut: 'Keyboard shortcut', procedure: 'Analysis procedure (ProcedureDef)', transform: 'Transform dialog', syntax: 'SPSS syntax command', 'ai-provider': 'AI provider',
  'ai-feature': 'AI feature', 'ai-error': 'AI error code', 'ai-tool': 'Assistant tool', 'ai-prompt': 'AI prompt builder', 'storage-key': 'Browser storage key',
  'output-kind': 'Output block kind', 'chart-type': 'Chart type (ChartSpec)', 'output-source': 'Output item source', 'palette-source': 'Search palette source', package: 'npm package', area: 'Area',
};

const PROP_LABELS = [
  ['path', 'Menu path'], ['shortcut', 'Shortcut'], ['requiresData', 'Needs a dataset'], ['conditional', 'Shown conditionally'], ['generated', 'Generated'], ['danger', 'Destructive'],
  ['hint', 'Tooltip'], ['menu', 'Menu'], ['description', 'Description'], ['does', 'Does'], ['menuLabel', 'Menu label'], ['toolKind', 'Tool kind'], ['compact', 'In compact tool set'],
  ['combo', 'Keys'], ['scope', 'Scope'], ['backend', 'Backend'], ['store', 'Store'], ['kind', 'Dialog kind'], ['dialogId', 'Dialog id'], ['routed', 'Has a renderer'], ['problem', 'Problem'],
  ['hasMessage', 'Has a user message'], ['idPrefix', 'Entry id prefix'], ['exported', 'Exported'], ['doc', 'Doc'], ['summary', 'Summary'], ['loc', 'Lines'], ['testCount', 'Test cases'],
];

function edgeSections(notes, g, id, skip = new Set(), limit = 120) {
  const out = [];
  const self = g.get(id);
  // inside a module note, links to the module's own symbols are listed under Symbols; inside a symbol's
  // note, the link to its own module (folded private helpers) is already in the header
  const local = (other) =>
    self && ((MODULE_TYPES.has(self.type) && g.get(other)?.file === self.file && other !== id) || (!MODULE_TYPES.has(self.type) && self.file && other === `module:${self.file}`));
  const outs = g.out(id).filter((e) => !local(e.target));
  const ins = g.in(id).filter((e) => !local(e.source));
  const fmt = (list, other) => {
    const items = list
      .map((e) => {
        const target = other(e);
        const via = e.via?.length ? ` · ${e.via.join(', ')}` : '';
        return [displayName(g.get(target), target), `- ${notes.link(target)}${via}`];
      })
      .sort((a, b) => a[0].localeCompare(b[0]) || a[1].localeCompare(b[1]))
      .map((x) => x[1]);
    const uniq = [...new Set(items)];
    return uniq.length > limit ? [...uniq.slice(0, limit), `- … and ${uniq.length - limit} more (see graph.json)`] : uniq;
  };
  for (const t of EDGE_ORDER) {
    if (skip.has(`out:${t}`)) continue;
    const list = outs.filter((e) => e.type === t);
    if (list.length) out.push(`## ${EDGE_LABELS[t][0]}`, ...fmt(list, (e) => e.target), '');
  }
  for (const t of EDGE_ORDER) {
    if (skip.has(`in:${t}`)) continue;
    const list = ins.filter((e) => e.type === t);
    if (list.length) out.push(`## ${EDGE_LABELS[t][1]}`, ...fmt(list, (e) => e.source), '');
  }
  return out;
}

function propLines(n) {
  const out = [];
  for (const [k, label] of PROP_LABELS) {
    const v = n[k];
    if (v === undefined || v === null || v === '' || k === 'summary' || k === 'doc') continue;
    out.push(`- **${label}:** ${Array.isArray(v) ? v.join(', ') : v === true ? 'yes' : v === false ? 'no' : String(v).replace(/\n/g, ' ')}`);
  }
  return out;
}

function genericNote(notes, g, n, extraBody = []) {
  const lines = [frontMatter(n)];
  lines.push(`# ${displayName(n, n.id)}`, '');
  lines.push(`*${TYPE_TITLES[n.type] ?? n.type}*${n.file ? ` · defined in ${notes.link(`module:${n.file}`)}${n.line ? ` (line ${n.line})` : ''}` : ''}${n.area ? ` · area ${notes.link(`area:${n.area}`)}` : ''}`, '');
  if (n.doc) lines.push(`> ${n.doc}`, '');
  if (n.summary) lines.push(`> ${n.summary}`, '');
  const props = propLines(n);
  if (props.length) lines.push(...props, '');
  lines.push(...extraBody);
  lines.push(...edgeSections(notes, g, n.id, new Set(['in:contains'])));
  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

function moduleNote(notes, g, n) {
  const lines = [frontMatter(n)];
  lines.push(`# ${n.file}`, '');
  lines.push(`*${TYPE_TITLES[n.type]}* · area ${notes.link(`area:${n.area}`)} · ${n.loc} lines`, '');
  if (n.summary) lines.push(`> ${n.summary}`, '');
  if (n.tests?.length) {
    lines.push('## Test cases', ...n.tests.map((t) => (t.startsWith('## ') ? `- **${t.slice(3)}**` : `  - ${t}`)), '');
  }
  lines.push(...edgeSections(notes, g, n.id, new Set(['out:contains', 'out:in-area'])));
  const priv = (g.privates?.get(n.id) ?? []).sort((a, b) => (a.line ?? 0) - (b.line ?? 0) || a.label.localeCompare(b.label));
  const typesList = priv.filter((p) => ['type', 'interface', 'enum'].includes(p.type));
  const helpers = priv.filter((p) => !typesList.includes(p));
  if (typesList.length) lines.push('## Types', typesList.map((p) => `${p.label}${p.exported ? '' : ' (private)'} (line ${p.line})`).join(' · '), '');
  if (helpers.length) lines.push('## Private helpers', helpers.map((p) => `${p.label}${p.type === 'function' ? '()' : ''} (line ${p.line})`).join(' · '), '');
  const syms = g.out(n.id, 'contains').map((e) => g.get(e.target)).filter(Boolean).sort((a, b) => (a.line ?? 0) - (b.line ?? 0) || a.label.localeCompare(b.label));
  if (syms.length) {
    lines.push('## Symbols', '');
    for (const s of syms) {
      lines.push(`### ${s.label}`);
      const own = notes.paths.get(s.id);
      lines.push(`*${s.type}*${s.line ? ` · line ${s.line}` : ''}${s.exported ? ' · exported' : ''}${own ? ` · note: ${notes.link(s.id)}` : ''}`);
      if (s.doc) lines.push(`> ${s.doc}`);
      const rel = [];
      const group = (dir, types, label) => {
        const list = (dir === 'out' ? g.out(s.id) : g.in(s.id)).filter((e) => types.includes(e.type));
        const ids = [...new Set(list.map((e) => (dir === 'out' ? e.target : e.source)))];
        const external = ids.filter((x) => dir === 'out' || g.get(x)?.file !== n.file);
        if (!external.length) return;
        const sorted = external.map((x) => notes.link(x)).sort();
        rel.push(`- ${label}: ${sorted.length > 25 ? sorted.slice(0, 25).join(', ') + ` … +${sorted.length - 25}` : sorted.join(', ')}`);
      };
      group('out', ['renders'], 'Renders');
      group('out', ['calls'], 'Calls');
      group('out', ['uses'], 'Uses');
      group('out', ['reads'], 'Reads');
      group('out', ['writes', 'removes'], 'Writes');
      group('out', ['calls-action'], 'Store actions');
      group('out', ['opens'], 'Opens');
      group('out', ['creates', 'handles'], 'Output');
      group('in', ['renders'], 'Rendered by');
      const usedIn = [...new Set(g.in(s.id).filter((e) => ['calls', 'uses'].includes(e.type)).map((e) => g.get(e.source)?.file).filter((f) => f && f !== n.file))].sort();
      if (usedIn.length) rel.push(`- Used in: ${usedIn.slice(0, 25).map((f) => notes.link(`module:${f}`)).join(', ')}${usedIn.length > 25 ? ` … +${usedIn.length - 25}` : ''}`);
      if (rel.length) lines.push(...rel);
      lines.push('');
    }
  }
  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

function areaNote(notes, g, n, report) {
  const lines = [frontMatter(n)];
  lines.push(`# Area: ${n.label}`, '');
  const mods = g.in(n.id, 'in-area').map((e) => g.get(e.source)).filter(Boolean).sort((a, b) => a.file.localeCompare(b.file));
  const loc = mods.reduce((s, m) => s + (m.loc ?? 0), 0);
  lines.push(`${mods.length} files, ${loc} lines.`, '');
  const outs = report.coupling.filter(([k]) => k.startsWith(`${n.label} -> `));
  const ins = report.coupling.filter(([k]) => k.endsWith(` -> ${n.label}`));
  if (outs.length) lines.push('## Depends on (module imports)', ...outs.map(([k, c]) => `- ${notes.link(`area:${k.split(' -> ')[1]}`)}: ${c}`), '');
  if (ins.length) lines.push('## Used by areas', ...ins.map(([k, c]) => `- ${notes.link(`area:${k.split(' -> ')[0]}`)}: ${c}`), '');
  lines.push('## Files', ...mods.map((m) => `- ${notes.link(m.id)}${m.summary ? `: ${m.summary.slice(0, 140)}${m.summary.length > 140 ? '…' : ''}` : ''}`), '');
  const byType = new Map();
  for (const m of mods) {
    for (const e of g.out(m.id, 'contains')) {
      const s = g.get(e.target);
      if (!s || !['component', 'hook', 'store'].includes(s.type)) continue;
      if (!byType.has(s.type)) byType.set(s.type, []);
      byType.get(s.type).push(s);
    }
  }
  for (const [t, list] of [...byType.entries()].sort()) {
    lines.push(`## ${t === 'component' ? 'Components' : t === 'hook' ? 'Hooks' : 'Stores'}`, list.sort((a, b) => a.label.localeCompare(b.label)).map((s) => notes.link(s.id)).join(' · '), '');
  }
  return lines.join('\n').trimEnd() + '\n';
}

function procedureBody(facts, notes, n) {
  const p = facts.procs.find((x) => `procedure:${x.id}` === n.id);
  if (!p) return [];
  const out = [];
  if (p.guidance) out.push(`> ${p.guidance}`, '');
  if (p.slots.length) out.push('## Variable slots', '| key | label | min | max | types | measures |', '|---|---|---|---|---|---|', ...p.slots.map((s) => `| ${s.key} | ${s.label ?? ''} | ${s.min ?? ''} | ${s.max ?? ''} | ${(s.types ?? []).join(', ')} | ${(s.measures ?? []).join(', ')} |`), '');
  if (p.options.length) out.push('## Options', '| key | type | label | group | default |', '|---|---|---|---|---|', ...p.options.map((o) => `| ${o.key} | ${o.type} | ${(o.label ?? '').replace(/\|/g, '/')} | ${o.group ?? ''} | ${o.default === undefined ? '' : JSON.stringify(o.default)} |`), '');
  void notes;
  return out;
}

function storeBody(facts, notes, n) {
  const name = n.id.startsWith('settings:') ? n.id.slice(9) : n.label;
  const st = facts.storeInfo.stores.get(name);
  if (!st) return [];
  const g = facts.g;
  const out = ['## Keys and who touches them', '| key | written by | read by |', '|---|---|---|'];
  for (const k of [...st.keys.keys()].sort()) {
    const id = `store-key:${name}.${k}`;
    const w = [...new Set(g.in(id, 'writes').map((e) => e.source))];
    const r = [...new Set(g.in(id, 'reads').map((e) => e.source))];
    out.push(`| ${notes.link(id, k)} | ${w.length} ${w.length ? '(' + w.slice(0, 4).map((x) => notes.link(x)).join(', ') + (w.length > 4 ? ', …' : '') + ')' : ''} | ${r.length} |`);
  }
  out.push('', '## Actions', '| action | writes | callers |', '|---|---|---|');
  for (const k of [...st.actions.keys()].sort()) {
    const id = `store-action:${name}.${k}`;
    const w = g.out(id, 'writes').map((e) => notes.link(e.target, e.target.split('.').pop()));
    out.push(`| ${notes.link(id, k + '()')} | ${w.join(', ')} | ${new Set(g.in(id, 'calls-action').map((e) => e.source)).size} |`);
  }
  out.push('');
  return out;
}

/**
 * The graph as published: private (non-exported) functions and constants are folded into their module,
 * so their edges become module edges. Components, hooks and stores stay even when private.
 */
export function publishedGraph(g) {
  const TYPE_KINDS = new Set(['type', 'interface', 'enum']);
  const CODE_EDGE = (id) => id.startsWith('sym:') || id.startsWith('module:');
  // private helpers stay visible when a domain node points at them (a dialog renders them, a tool runs them...)
  const domainLinked = new Set();
  for (const e of g.edges.values()) {
    if (e.target.startsWith('sym:') && !CODE_EDGE(e.source) && !e.source.startsWith('area:')) domainLinked.add(e.target);
    if (e.source.startsWith('sym:') && !CODE_EDGE(e.target) && !e.target.startsWith('area:') && e.type !== 'calls-action' && e.type !== 'reads' && e.type !== 'writes') domainLinked.add(e.source);
  }
  const keep = (n) =>
    !(n.id.startsWith('sym:') && (TYPE_KINDS.has(n.type) || (!n.exported && !['component', 'hook', 'store'].includes(n.type) && !domainLinked.has(n.id))));
  const pg = new Graph();
  const privates = new Map(); // module id -> [private symbol nodes]
  for (const n of g.nodes.values()) {
    if (keep(n)) pg.nodes.set(n.id, n);
    else {
      const m = `module:${n.file}`;
      if (!privates.has(m)) privates.set(m, []);
      privates.get(m).push(n);
    }
  }
  const remap = (id) => {
    const n = g.get(id);
    return n && !keep(n) ? `module:${n.file}` : id;
  };
  for (const e of g.sortedEdges()) {
    const s = remap(e.source);
    const t = remap(e.target);
    if (s === t || !pg.has(s) || !pg.has(t)) continue;
    if (e.type === 'contains' && t !== e.target) continue;
    pg.edge(s, t, e.type, { via: e.via });
  }
  pg.freeze();
  pg.privates = privates;
  pg.folded = (id) => {
    const n = g.get(id);
    return n && !keep(n) ? n : null;
  };
  return pg;
}

export function emitAll(facts, report, outDir, opts = {}) {
  facts.g.freeze();
  const g = publishedGraph(facts.g);
  const full = facts.g;
  facts = { ...facts, g, full };
  const notes = new Notes(g);
  const files = new Map();
  for (const n of g.sortedNodes()) {
    const p = notes.paths.get(n.id);
    if (!p) continue;
    let body;
    if (MODULE_TYPES.has(n.type)) body = moduleNote(notes, g, n);
    else if (n.type === 'area') body = areaNote(notes, g, n, report);
    else if (n.type === 'procedure') body = genericNote(notes, g, n, procedureBody(facts, notes, n));
    else if (n.type === 'store') body = genericNote(notes, g, n, storeBody(facts, notes, n));
    else body = genericNote(notes, g, n);
    files.set(`${p}.md`, escapeTableLinks(body));
  }
  files.set('GRAPH_REPORT.md', escapeTableLinks(notes.resolveTokens(renderReport(facts, report, notes))));
  files.set('DIAGRAMS.md', renderDiagrams(facts, report, notes));
  files.set('README.md', renderReadme(facts, report));
  files.set('Home.md', renderHome(facts, report, notes));
  files.set('graph.json', renderGraphJson(g, facts));
  // Obsidian writes its workspace state into .obsidian/; only the preset graph colours are worth keeping
  files.set('.gitignore', '.obsidian/*\n!.obsidian/graph.json\n');
  return writeFiles(outDir, files, opts);
}

// Structural edges that the node fields already say (node.file, node.area) are left out of graph.json.
// Calls and uses inside one file are left out too (read the file); renders between components are kept.
const JSON_SKIP_EDGES = new Set(['contains', 'in-area']);

/** graph.json ids: a module is its path, a symbol is path#name; everything else keeps its prefix (cmd:, store-key:...). */
export const jsonId = (id) => (id.startsWith('module:') ? id.slice(7) : id.startsWith('sym:') ? id.slice(4) : id);
const fileOfId = (id) => (id.startsWith('sym:') ? id.slice(4).split('#')[0] : id.startsWith('module:') ? id.slice(7) : null);
const sameFile = (a, b) => {
  const fa = fileOfId(a);
  return !!fa && fa === fileOfId(b);
};

function renderGraphJson(g, facts) {
  const KEEP = ['label', 'type', 'file', 'line', 'area', 'exported', 'store', 'menu', 'path', 'shortcut', 'requiresData', 'kind', 'dialogId', 'routed', 'problem', 'procedureId', 'toolKind', 'compact', 'backend', 'combo', 'scope', 'hasMessage', 'loc', 'testCount', 'summary'];
  const nodes = g.sortedNodes().map((n) => {
    const o = { id: jsonId(n.id) };
    for (const k of KEEP) {
      if (n[k] === undefined || n[k] === '') continue;
      if (n.id.startsWith('sym:') && k === 'area') continue; // derivable from file
      if (k === 'exported' && n.type !== 'component' && n.type !== 'hook' && n.type !== 'store') continue; // other symbols in graph.json are all exported
      if (k === 'summary' && !n.id.startsWith('module:')) continue;
      o[k === 'file' ? 'source_file' : k] = typeof n[k] === 'string' && n[k].length > 160 ? n[k].slice(0, 157) + '...' : n[k];
    }
    return JSON.stringify(o);
  });
  const edges = g
    .sortedEdges()
    .filter((e) => !JSON_SKIP_EDGES.has(e.type) && !(e.type !== 'renders' && sameFile(e.source, e.target)))
    // a test importing a source module is already recorded as `tested-by` (source -> test)
    .filter((e) => !(e.type === 'imports' && /^module:(tests|e2e)\//.test(e.source) && e.target.startsWith('module:src/')))
    // symbol-level edges from test code (which function a test calls) stay in the vault notes only
    .filter((e) => !(/^(module|sym):(tests|e2e)\//.test(e.source) && ['calls', 'uses', 'reads', 'writes', 'calls-action', 'renders'].includes(e.type)))
    .map((e) => {
      // default qualifiers are omitted: imports are value imports, tested-by is by import, unless `via` says otherwise
      const via = e.via?.filter((v) => !((e.type === 'imports' && v === 'value') || (e.type === 'tested-by' && v === 'import')));
      return JSON.stringify(via?.length ? { source: jsonId(e.source), target: jsonId(e.target), relation: e.type, via } : { source: jsonId(e.source), target: jsonId(e.target), relation: e.type });
    });
  const meta = { name: 'socius', generator: 'scripts/map/build-map.mjs (npm run map)', typescript: facts.tsVersion, note: 'Node-link format (networkx / graphify compatible). Edge "relation" = relationship type; see docs/map/README.md. Ids: a module is its path, a symbol is path#name, other ids have a type prefix. Module membership and area are node fields (source_file, area), not edges; calls/uses inside one file are omitted; a test importing a source module appears only as the tested-by edge of that module (symbol-level calls from tests are in the vault notes). Private helpers are folded into their module.' };
  return `{\n"directed": true,\n"multigraph": false,\n"graph": ${JSON.stringify(meta)},\n"nodes": [\n${nodes.join(',\n')}\n],\n"links": [\n${edges.join(',\n')}\n]\n}\n`;
}

function listFiles(dir, base = dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    const abs = path.join(dir, name);
    const rel = path.relative(base, abs).split(path.sep).join('/');
    if (rel === '.obsidian' || rel.startsWith('.obsidian/')) continue;
    if (statSync(abs).isDirectory()) listFiles(abs, base, out);
    else out.push(rel);
  }
  return out;
}

function writeFiles(outDir, files, { check }) {
  const existing = new Set(listFiles(outDir));
  const changed = [];
  let bytes = 0;
  for (const [rel, content] of [...files.entries()].sort()) {
    bytes += Buffer.byteLength(content);
    const abs = path.join(outDir, rel);
    const prev = existing.has(rel) ? readFileSync(abs, 'utf8') : null;
    existing.delete(rel);
    if (prev === content) continue;
    changed.push(rel);
    if (check) continue;
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, content);
  }
  const stale = [...existing];
  if (!check) {
    for (const rel of stale) rmSync(path.join(outDir, rel));
    pruneEmptyDirs(outDir);
    const obs = path.join(outDir, '.obsidian', 'graph.json');
    if (!existsSync(obs)) {
      mkdirSync(path.dirname(obs), { recursive: true });
      writeFileSync(obs, JSON.stringify(OBSIDIAN_GRAPH, null, 2) + '\n');
    }
  }
  const g = files.get('graph.json');
  const counts = g.match(/\n"nodes": \[\n([\s\S]*?)\n\],\n"links": \[\n([\s\S]*?)\n\]/);
  return { changed: [...changed, ...stale], removed: stale.length, files: files.size, bytes, nodes: counts ? counts[1].split('\n').length : 0, edges: counts ? counts[2].split('\n').length : 0 };
}

function pruneEmptyDirs(dir) {
  for (const name of readdirSync(dir)) {
    const abs = path.join(dir, name);
    if (name === '.obsidian' || !statSync(abs).isDirectory()) continue;
    pruneEmptyDirs(abs);
    if (!readdirSync(abs).length) rmSync(abs, { recursive: true });
  }
}
