// GRAPH_REPORT.md: the facts agents need most, and the bug leads (inconsistencies and orphans).

import { NOISE_ACTIONS } from './extract-ui.mjs';

const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function renderReport(facts, report, notes) {
  const { g, index, procs, transforms, ai, storage, output, shortcuts, storeInfo, menuInfo } = facts;
  const isTestFile = (id) => ['test', 'e2e-spec'].includes(g.get(id)?.type);
  const L = (id, alias) => notes.link(id, alias);
  const out = [];
  const push = (...x) => out.push(...x);

  push('# Socius graph report', '');
  push(`Generated by \`npm run map\` (scripts/map/build-map.mjs) from the TypeScript sources with the TypeScript ${facts.tsVersion} compiler API. Do not edit by hand: rerun the generator. How to read and regenerate: [[README]]. Big picture: [[DIAGRAMS]]. Vault start page: [[Home]].`, '');

  // ---------- at a glance ----------
  const srcFiles = [...index.files.values()].filter((f) => f.rel.startsWith('src/'));
  const testFiles = [...index.files.values()].filter((f) => f.isTest);
  const nodeTypes = count([...g.nodes.values()].map((n) => n.type));
  const edgeTypes = count([...g.edges.values()].map((e) => e.type));
  push('## At a glance', '');
  push(`- ${srcFiles.length} source files (${srcFiles.reduce((s, f) => s + f.ft.lines.length, 0)} lines) in ${new Set(srcFiles.map((f) => f.area)).size} areas; ${testFiles.length} test and e2e files.`);
  push(`- ${g.nodes.size} nodes and ${g.edges.size} edges. ${procs.length} procedures, ${transforms.length} transform dialogs, ${menuInfo.commands.length} menu entries, ${storeInfo.stores.size} stores, ${ai.tools.length} assistant tools.`);
  push(`- ${report.issues.filter((i) => i.severity !== 'info').reduce((s, i) => s + i.items.length, 0)} bug leads in ${report.issues.filter((i) => i.severity !== 'info').length} categories (plus ${report.issues.filter((i) => i.severity === 'info').reduce((s, i) => s + i.items.length, 0)} informational items), listed below.`);
  if (index.missing.length) push(`- Files TypeScript could not load: ${index.missing.join(', ')}`);
  if (facts.warnings?.length) push(`- **Generator warnings** (these parts of the map are incomplete this run): ${facts.warnings.map((w) => `\`${w.slice(0, 200)}\``).join('; ')}`);
  push('');
  push('| node type | count |', '|---|---|', ...[...nodeTypes].map(([k, v]) => `| ${k} | ${v} |`), '');
  push('| edge relation | count |', '|---|---|', ...[...edgeTypes].map(([k, v]) => `| ${k} | ${v} |`), '');

  // ---------- bug leads ----------
  push('## Bug leads: inconsistencies and orphans', '');
  push('Each item is a lead to confirm in the code, found by cross-checking declarations against uses. Severity is a guess at user impact: **high** (a user-visible failure is likely), **medium** (dead or unreachable code, or a mismatch worth fixing), **low** (tidy-up), **info** (context, usually fine).', '');
  const order = { high: 0, medium: 1, low: 2, info: 3 };
  const cats = [...report.issues].sort((a, b) => order[a.severity] - order[b.severity] || a.category.localeCompare(b.category) || a.title.localeCompare(b.title));
  push('| severity | area | finding | count |', '|---|---|---|---|', ...cats.map((c) => `| ${c.severity} | ${c.category} | ${esc(c.title)} | ${c.items.length} |`), '');
  for (const c of cats) {
    push(`### ${c.title} (${c.severity}, ${c.items.length})`, '');
    if (c.note) push(`*${c.note}*`, '');
    const cap = c.severity === 'info' ? 80 : 400;
    push(...c.items.slice(0, cap).map((x) => `- ${x}`));
    if (c.items.length > cap) push(`- … and ${c.items.length - cap} more (rerun with a larger cap in scripts/map/lib/report.mjs)`);
    push('');
  }

  // ---------- entry points ----------
  push('## Entry points', '');
  const main = g.get('module:src/main.tsx');
  if (main) push(`- ${L('module:src/main.tsx')} mounts ${g.out('module:src/main.tsx', 'renders').map((e) => L(e.target)).join(', ') || 'the app'} (index.html loads it; Vite config: vite.config.ts).`);
  const app = [...g.nodes.values()].find((n) => n.id === 'sym:src/app/App.tsx#App');
  if (app) push(`- ${L(app.id)} renders ${g.out(app.id, 'renders').map((e) => L(e.target)).sort().join(', ')}.`);
  const globals = [...new Set(shortcuts.bound.filter((b) => b.scope === 'global').map((b) => b.from))].sort();
  push(`- Global key handlers: ${globals.map((x) => L(x)).join(', ')}.`);
  push(`- Stores: ${[...storeInfo.stores.values()].map((s) => `${L(s.nodeId)} (${s.keys.size} keys, ${s.actions.size} actions)`).join(', ')}.`);
  push(`- Dialog host${report.routeHosts?.length > 1 ? 's' : ''}: ${[...new Set(facts.routeInfo.hosts.map((h) => `sym:${h.f.rel}#${h.d.name}`))].map((x) => L(x)).join(', ')} (switch on \`dialog.kind\`).`);
  push('');

  // ---------- command table ----------
  push('## Menu command → dialog → action', '');
  push('Every menubar entry (the search palette lists the same commands with ids `cmd:<menu>:<item>`). "Does" lists opened dialogs, tab switches, store actions and functions called directly by the handler; `via` shows effects found by following a helper one level.', '');
  const byMenu = new Map();
  for (const c of menuInfo.commands) {
    if (!byMenu.has(c.menu)) byMenu.set(c.menu, []);
    byMenu.get(c.menu).push(c);
  }
  for (const [menu, list] of byMenu) {
    push(`### ${g.get(`menu:${menu}`)?.label ?? menu}`, '', '| command | keys | opens → rendered by | does |', '|---|---|---|---|');
    for (const c of list) {
      const n = g.get(c.id);
      if (!n || n.type === 'submenu') continue;
      const opens = g.out(c.id, 'opens').map((e) => {
        const r = g.out(e.target, 'rendered-by').map((x) => L(x.target));
        return `${L(e.target)} → ${r.length ? r.join(', ') : '**no renderer**'}`;
      });
      const does = [
        ...g.out(c.id, 'switches-to').map((e) => `tab \`${e.target.split(':').slice(1).join(':')}\``),
        ...g.out(c.id, 'calls-action').filter((e) => !(NOISE_ACTIONS.has(e.target.split('.').pop()) && e.via)).map((e) => L(e.target) + (e.via ? ` (via ${e.via.join(', ')})` : '')),
        ...g.out(c.id, 'writes').map((e) => `writes ${L(e.target)}` + (e.via ? ` (via ${e.via.join(', ')})` : '')),
        ...g.out(c.id, 'calls').map((e) => L(e.target) + (e.via ? ` ${e.via.join(' ')}` : '')),
      ];
      push(`| ${L(c.id, (n.path ?? n.label).split(' > ').slice(1).join(' > '))}${n.requiresData ? ' ¹' : ''}${n.conditional ? ' ²' : ''} | ${esc(n.shortcut ?? '')} | ${opens.join('<br>')} | ${[...new Set(does)].join(', ')} |`);
    }
    push('');
  }
  push('¹ disabled until a dataset is open. ² shown only in some states.', '');

  // ---------- dialogs ----------
  push('## Dialog routing', '');
  push('`openDialog({ kind, id })` requests go to the dialog host, which picks a component by kind, then by id (switch, if, or a registry object). Procedure ids all render through the generic procedure dialog.', '');
  push('| dialog | rendered by | opened by |', '|---|---|---|');
  const dialogs = [...g.nodes.values()].filter((n) => n.type === 'dialog' && n.kind !== 'procedure').sort((a, b) => a.id.localeCompare(b.id));
  for (const d of dialogs) {
    const r = g.out(d.id, 'rendered-by').map((e) => L(e.target) + (e.via ? ` (${e.via.join(', ')})` : ''));
    const o = [...new Set(g.in(d.id, 'opens').map((e) => e.source))].sort().map((x) => L(x));
    push(`| ${L(d.id)} | ${r.join(', ') || `**none**${d.problem ? `: ${esc(d.problem)}` : ''}`} | ${o.join(', ') || '*nothing*'} |`);
  }
  push('');

  // ---------- stores ----------
  push('## Store key ownership', '');
  push('Who writes each piece of state (actions, direct `setState`/`set`) and how many places read it, in production code (tests are left out here; the per-key notes list every reader and writer, tests included).', '');
  for (const st of [...storeInfo.stores.values()].sort((a, b) => a.name.localeCompare(b.name))) {
    push(`### ${L(st.nodeId, st.name)} (${st.file})`, '', '| key | written by | readers | read in |', '|---|---|---|---|');
    for (const k of [...st.keys.keys()].sort()) {
      const id = `store-key:${st.name}.${k}`;
      const prod = (e) => !/^(tests|e2e)\//.test(g.get(e.source)?.file ?? '');
      const w = [...new Set(g.in(id, 'writes').filter(prod).map((e) => e.source))].sort();
      const reads = g.in(id, 'reads').filter(prod);
      const r = [...new Set(reads.map((e) => g.get(e.source)?.file ?? e.source))].sort();
      push(`| ${L(id, k)} | ${w.map((x) => L(x)).join(', ') || '*initial value only*'} | ${reads.length} | ${r.slice(0, 6).map((f) => L(`module:${f}`, f.split('/').pop())).join(', ')}${r.length > 6 ? `, +${r.length - 6}` : ''} |`);
    }
    push('');
    if (st.actions.size) {
      push('| action | writes | callers |', '|---|---|---|');
      for (const k of [...st.actions.keys()].sort()) {
        const id = `store-action:${st.name}.${k}`;
        const callers = [...new Set(g.in(id, 'calls-action').map((e) => e.source))];
        push(`| ${L(id, k + '()')} | ${g.out(id, 'writes').map((e) => e.target.split('.').pop()).join(', ')} | ${callers.length} |`);
      }
      push('');
    }
  }

  // ---------- procedures ----------
  push('## Procedures (Analyze and Graphs menus)', '');
  push('| procedure | menu | stats / lib functions called | SPSS syntax | charts | tests |', '|---|---|---|---|---|---|');
  for (const p of procs) {
    const id = `procedure:${p.id}`;
    const calls = g.out(id, 'calls').filter((e) => e.target.startsWith('sym:src/lib/')).map((e) => L(e.target));
    const charts = new Set();
    for (const s of p.reached ?? []) for (const e of g.out(s, 'creates')) if (e.target.startsWith('chart-type:')) charts.add(e.target.slice(11));
    const tests = [...new Set(g.out(id, 'tested-by').map((e) => e.target))].filter(isTestFile).map((x) => L(x, x.split('/').pop()));
    push(`| ${L(id, `${p.title} (${p.id})`)} | ${esc(p.menu)} | ${calls.join(', ')} | ${p.syntax.join(', ')} | ${[...charts].sort().join(', ')} | ${tests.join(', ') || '**none**'} |`);
  }
  push('');

  // ---------- transforms ----------
  push('## Transforms (Data and Transform menus)', '');
  push('| transform | dialog component | lib functions | SPSS syntax | logged by | tests |', '|---|---|---|---|---|---|');
  for (const t of transforms) {
    const id = `transform:${t.id}`;
    const tests = [...new Set([...g.out(id, 'tested-by').map((e) => e.target), ...t.libCalls.flatMap((s) => g.out(`module:${s.slice(4).split('#')[0]}`, 'tested-by').map((e) => e.target))])].filter(isTestFile);
    push(`| ${L(id, t.id)} | ${t.comps.map((c) => L(c)).join(', ')} | ${t.libCalls.filter((s) => /^[a-z]/.test(s.split('#')[1])).map((s) => L(s)).join(', ')} | ${t.syntax.join(', ')} | ${t.logged.map((s) => L(s)).join(', ') || '**none**'} | ${tests.map((x) => L(x, x.split('/').pop())).join(', ') || '**none**'} |`);
  }
  push('');

  // ---------- AI ----------
  push('## AI', '');
  push('### Providers', '', '| provider | implemented in |', '|---|---|');
  for (const p of ai.providers) push(`| ${L(`ai-provider:${p.id}`)} | ${g.out(`ai-provider:${p.id}`, 'implemented-in').map((e) => L(e.target)).join(', ')} |`);
  push('', '### Features (AI menu)', '', '| feature | starts by | opens | writes |', '|---|---|---|---|');
  for (const f of ai.features) {
    const id = `ai-feature:${f.id}`;
    push(`| ${L(id, f.label)} | ${g.out(id, 'started-by').map((e) => L(e.target)).join(', ')} | ${g.out(id, 'opens').map((e) => L(e.target)).join(', ')} | ${g.out(id, 'writes').map((e) => L(e.target)).join(', ')} |`);
  }
  push('', '### Assistant tools', '', '| tool | kind | implementation | reads app state | needs permission | tests |', '|---|---|---|---|---|---|');
  for (const t of [...ai.tools].sort((a, b) => a.name.localeCompare(b.name))) {
    const id = `ai-tool:${t.name}`;
    push(`| ${L(id, t.name)}${t.compact ? ' ᶜ' : ''} | ${t.kind ?? ''} | ${g.out(id, 'implemented-by').map((e) => L(e.target)).join(', ')} | ${(t.reads ?? []).join(', ')} | ${(t.perms ?? []).join(', ')} | ${[...new Set(g.out(id, 'tested-by').map((e) => e.target))].filter(isTestFile).map((x) => L(x, x.split('/').pop())).join(', ') || '**none**'} |`);
  }
  push('', 'ᶜ offered to the on-device model (compact tool set).', '');
  push('### Error codes', '', '| code | user message | produced by | checked by |', '|---|---|---|---|');
  const codes = [...new Set([...ai.errors.defined.keys(), ...ai.errors.thrown.keys()])].sort();
  for (const c of codes) {
    const prod = [...(ai.errors.thrown.get(c) ?? [])].sort().map((x) => L(x));
    const chk = [...(ai.errors.checked.get(c) ?? [])].sort().map((x) => L(x));
    push(`| ${L(`ai-error:${c}`, c)} | ${ai.errors.defined.has(c) ? 'yes' : c === 'unavailable' ? 'default text' : '**missing**'} | ${prod.join(', ') || '*none*'} | ${chk.join(', ')} |`);
  }
  push('', '### Prompt builders', '', ...ai.prompts.map((p) => `- ${L(p.id)} in ${L(`module:${p.file}`)}; used by ${[...new Set(g.in(`sym:${p.file}#${p.name}`).filter((e) => ['calls', 'uses'].includes(e.type)).map((e) => e.source))].map((x) => L(x)).join(', ') || '*nothing*'}`), '');

  // ---------- storage ----------
  push('## Browser storage', '', 'localStorage keys, IndexedDB object stores and who reads or writes them (through wrappers such as readPref/writePref).', '');
  push('| key | backend | writes | reads | other |', '|---|---|---|---|---|');
  const skeys = [...g.nodes.values()].filter((n) => n.type === 'storage-key').sort((a, b) => a.id.localeCompare(b.id));
  for (const k of skeys) {
    const by = (t) => [...new Set(g.in(k.id, t).map((e) => e.source))].sort().map((x) => L(x));
    push(`| ${L(k.id, k.label)} | ${k.backend} | ${by('writes').join(', ')} | ${by('reads').join(', ')} | ${[...by('removes').map((x) => 'removes: ' + x), ...by('listens').map((x) => 'listens: ' + x)].join(', ')} |`);
  }
  push('');
  void storage;

  // ---------- output ----------
  push('## Output model', '', `Block kinds and chart types come from the unions in ${output.file ? L(`module:${output.file}`) : 'core/output.ts'}. "Renderers" and "exporters" are modules that branch on the kind/type.`, '');
  push('| block / chart | created in | renderers (UI) | exporters | other consumers |', '|---|---|---|---|---|');
  const modsOf = (id, type, pred) => [...new Set(g.in(id, type).filter(pred ?? (() => true)).map((e) => g.get(e.source)?.file ?? e.source))].sort();
  for (const id of [...output.blockKinds.map((k) => `output-kind:${k}`), ...output.chartTypes.map((t) => `chart-type:${t}`)]) {
    const created = modsOf(id, 'creates');
    const rend = modsOf(id, 'handles', (e) => e.via?.includes('renderer'));
    const exp = modsOf(id, 'handles', (e) => e.via?.includes('exporter'));
    const other = modsOf(id, 'handles', (e) => e.via?.includes('consumer'));
    const f = (list) => list.map((x) => L(`module:${x}`, x.split('/').pop())).join(', ');
    push(`| ${L(id)} | ${f(created)} | ${f(rend) || '*generic*'} | ${f(exp) || '*generic*'} | ${f(other)} |`);
  }
  push('');

  // ---------- shortcuts ----------
  push('## Keyboard shortcuts', '', 'Documented = Help > Keyboard shortcuts tables and menu labels. Bound = key comparisons in key handlers (global = registered on window/document).', '');
  push('| keys | documented | bound globally in | bound locally in |', '|---|---|---|---|');
  const combos = new Set([...shortcuts.documented.map((d) => d.combo), ...shortcuts.bound.filter((b) => /^(Mod|Alt)\+|^\/$|^F\d/.test(b.combo) || b.scope === 'global').map((b) => b.combo)]);
  for (const c of [...combos].sort()) {
    const docs = [...new Set(shortcuts.documented.filter((d) => d.combo === c).map((d) => d.group))].sort();
    const gl = [...new Set(shortcuts.bound.filter((b) => b.combo === c && b.scope === 'global').map((b) => b.from))].sort().map((x) => L(x));
    const lo = [...new Set(shortcuts.bound.filter((b) => b.combo === c && b.scope !== 'global').map((b) => b.from))].sort().map((x) => L(x));
    push(`| \`${c}\` | ${docs.join(', ') || '*no*'} | ${gl.join(', ')} | ${lo.slice(0, 8).join(', ')}${lo.length > 8 ? ` +${lo.length - 8}` : ''} |`);
  }
  push('');

  // ---------- structure ----------
  push('## Structure: coupling and hot spots', '');
  push('### Area → area imports (module level)', '', '| from → to | imports |', '|---|---|', ...report.coupling.slice(0, 40).map(([k, v]) => `| ${k} | ${v} |`), '');
  push('### Most imported modules', '', ...report.fanIn.map(([id, n]) => `- ${L(id)}: imported by ${n} files`), '');
  push('### Modules with most imports', '', ...report.fanOut.map(([id, n]) => `- ${L(id)}: imports ${n} files`), '');
  push('### Most widely used symbols (distinct files using them)', '', ...report.symFanIn.map(([id, n]) => `- ${L(id)}: ${n} files`), '');
  push(`Unused exported types and interfaces (not listed): ${report.deadTypes}.`, '');

  // ---------- tests ----------
  push('## Test coverage by area (direct imports from test files)', '');
  push('| area | source files | imported by a test | share |', '|---|---|---|---|');
  const areas = new Map();
  for (const f of srcFiles) {
    if (!areas.has(f.area)) areas.set(f.area, [0, 0]);
    const a = areas.get(f.area);
    a[0]++;
    if (g.out(`module:${f.rel}`, 'tested-by').length) a[1]++;
  }
  for (const [a, [n, t]] of [...areas].sort()) push(`| ${L(`area:${a}`, a)} | ${n} | ${t} | ${Math.round((100 * t) / n)}% |`);
  push('');
  push('### Test files', '', ...testFiles.map((f) => `- ${L(`module:${f.rel}`)}: ${g.get(`module:${f.rel}`)?.testCount ?? 0} cases`), '');
  return out.join('\n').replace(/\n{3,}/g, '\n\n');
}

function count(list) {
  const m = new Map();
  for (const x of list) m.set(x, (m.get(x) ?? 0) + 1);
  return new Map([...m].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])));
}
